### ISSUE TITLE
Should "Axes" only include dimension coordinates?

### ISSUE THREAD

**Issue by malmans2** [xarray-contrib/cf-xarray#171] opened 2021-02-08 16:34 UTC
Here is an example showing why non-dimension coordinates in Axes can be an issue.
I think in this case `t` should be the only axis.

```python
import xarray as xr
import cf_xarray
from datetime import date
```

```python
ds = xr.Dataset(
    {"t": xr.DataArray([1], dims="t", attrs=dict(axis="T"))}
)
ds = ds.assign_coords(
    time=xr.DataArray([date.today()], dims="t", attrs=dict(standard_name="time"))
)
ds.cf
```

    Coordinates:
    - CF Axes:   T: ['t', 'time']
                 X, Y, Z: n/a
    
    - CF Coordinates:   time: ['time']
                        longitude, latitude, vertical: n/a
    
    - Cell Measures:   area, volume: n/a
    
    - Standard Names:   time: ['time']
    
    Data Variables:
    - Cell Measures:   area, volume: n/a
    
    - Standard Names:   n/a

```python
ds.cf.squeeze("T")
```

    ---------------------------------------------------------------------------

    KeyError                                  Traceback (most recent call last)

    <ipython-input-3-ab90adea14ff> in <module>
    ----> 1 ds.cf.squeeze("T")
    

    ~/MyGit/cf-xarray/cf_xarray/accessor.py in wrapper(*args, **kwargs)
        536         )
        537         final_func = extra_decorator(func) if extra_decorator else func
    --> 538         result = final_func(*posargs, **arguments)
        539         if wrap_classes and isinstance(result, _WRAPPED_CLASSES):
        540             result = _CFWrappedClass(result, accessor)

    ~/anaconda3/envs/cf_xarray_test/lib/python3.9/site-packages/xarray/core/common.py in squeeze(self, dim, drop, axis)
        365         numpy.squeeze
        366         """
    --> 367         dims = get_squeeze_dims(self, dim, axis)
        368         return self.isel(drop=drop, **{d: 0 for d in dims})
        369 

    ~/anaconda3/envs/cf_xarray_test/lib/python3.9/site-packages/xarray/core/common.py in get_squeeze_dims(xarray_obj, dim, axis)
        320         dim = [alldims[a] for a in axis]
        321 
    --> 322     if any(xarray_obj.sizes[k] > 1 for k in dim):
        323         raise ValueError(
        324             "cannot select a dimension to squeeze out "

    ~/anaconda3/envs/cf_xarray_test/lib/python3.9/site-packages/xarray/core/common.py in <genexpr>(.0)
        320         dim = [alldims[a] for a in axis]
        321 
    --> 322     if any(xarray_obj.sizes[k] > 1 for k in dim):
        323         raise ValueError(
        324             "cannot select a dimension to squeeze out "

    ~/anaconda3/envs/cf_xarray_test/lib/python3.9/site-packages/xarray/core/utils.py in __getitem__(self, key)
        424 
        425     def __getitem__(self, key: K) -> V:
    --> 426         return self.mapping[key]
        427 
        428     def __iter__(self) -> Iterator[K]:

    ~/anaconda3/envs/cf_xarray_test/lib/python3.9/site-packages/xarray/core/utils.py in __getitem__(self, key)
        455 
        456     def __getitem__(self, key: K) -> V:
    --> 457         return self.mapping[key]
        458 
        459     def __setitem__(self, key: K, value: V) -> None:

    KeyError: 'time'

**Comment by dcherian** [comment] 2021-02-08 17:37
This is basically a dupe of #107. I'll respond there.

**Closed by dcherian** 2021-02-08 17:37 UTC
